name: ci-only

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.13.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Setup
        run: sh ./contrib/ci.sh
      - name: Run CI
        run: make
      - name: After Success
        run: |
          if [ -z $DOCKER_NS ] ; then
            export DOCKER_NS=openfaas;
            fi
          
          
          # if [ ! -z "$TRAVIS_TAG" ] ; then 
          #     docker tag $DOCKER_NS/faas-swarm:latest-dev $DOCKER_NS/faas-swarm:$TRAVIS_TAG;
          #     echo $DOCKER_PASSWORD | docker login -u=$DOCKER_USERNAME --password-stdin;
          #     docker push $DOCKER_NS/faas-swarm:$TRAVIS_TAG;
          #     docker tag $DOCKER_NS/faas-swarm:latest-dev quay.io/$DOCKER_NS/faas-swarm:$TRAVIS_TAG;
          #     echo $QUAY_PASSWORD | docker login -u=$QUAY_USERNAME --password-stdin quay.io;
          #     docker push quay.io/$DOCKER_NS/faas-swarm:$TRAVIS_TAG;
          #     fi