name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    strategy:
      matrix:
        go-version: [1.13.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Get TAG
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - name: Set Docker Namespace
        id: get_docker_ns
        env:
          GITHUB_ACTOR: ${{ github.actor }}
        run: echo ::set-output name=DOCKER_NS::${GITHUB_ACTOR}
      - name: Setup
        run: sh ./contrib/ci.sh
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to Quay Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io
      - name: Login to Github Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_PASSWORD }}
          registry: ghcr.io
      - name: Push containers
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            http_proxy=8080
            https_proxy=8443
          push: true
          tags: |
            ${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:${{ github.sha }}
            ${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:${{ steps.get_tag.outputs.TAG }}
            ${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:latest
            quay.io/${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:${{ github.sha }}
            quay.io/${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:${{ steps.get_tag.outputs.TAG }}
            quay.io/${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:latest
            ghcr.io/${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:${{ github.sha }}
            ghcr.io/${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:${{ steps.get_tag.outputs.TAG }}
            ghcr.io/${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:latest
      - name: Push containers arm64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.arm64
          build-args: |
            http_proxy=8080
            https_proxy=8443
          push: true
          tags: |
            ${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:${{ github.sha }}-arm64
            ${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:${{ steps.get_tag.outputs.TAG }}-arm64
            ${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:latest-arm64
            quay.io/${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:${{ github.sha }}-arm64
            quay.io/${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:${{ steps.get_tag.outputs.TAG }}-arm64
            quay.io/${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:latest-arm64
            ghcr.io/${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:${{ github.sha }}-arm64
            ghcr.io/${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:${{ steps.get_tag.outputs.TAG }}-arm64
            ghcr.io/${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:latest-arm64
      - name: Push containers armhf
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.armhf
          build-args: |
            http_proxy=8080
            https_proxy=8443
          push: true
          tags: |
            ${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:${{ github.sha }}-armhf
            ${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:${{ steps.get_tag.outputs.TAG }}-armhf
            ${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:latest-armhf
            quay.io/${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:${{ github.sha }}-armhf
            quay.io/${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:${{ steps.get_tag.outputs.TAG }}-armhf
            quay.io/${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:latest-armhf
            ghcr.io/${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:${{ github.sha }}-armhf
            ghcr.io/${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:${{ steps.get_tag.outputs.TAG }}-armhf
            ghcr.io/${{ steps.get_docker_ns.output.DOCKER_NS }}/faas-swarm:latest-armhf